/* ════════════════════════════════════════════════════════════
   فهرس التخصّصات الجامعية — **أسماء فقط**

   ⚠️ هذا الملفّ يحمل **الأسماء والمجالات وحدها**، ولا يحمل أي نصّ
   وصفي. النصوص الوصفية في الملفّ الذي رُفع تعود لموقع طرف ثالث
   (bac-story)، ونشرها نسخٌ لا يجوز — فحُذفت كلّها.

   ما بقي هنا واقعة عامّة: قائمة التخصّصات الجامعية في الجزائر
   وأسماؤها. لا يملكها أحد، تماماً كقائمة الولايات.

   **المحتوى تكتبه أنت** من لوحة الإدارة، ويُخزَّن في قاعدة البيانات.
   الفهرس يبقى ليعمل البحث والتصنيف من أوّل يوم بلا انتظار.
════════════════════════════════════════════════════════════ */

export interface SpecLite { slug: string; ar: string; fr: string; field: string }

export const SPEC_INDEX: SpecLite[] = [
  {"slug": "forensique", "ar": "الأدلة الجنائية والشرطة العلمية", "fr": "Sciences Forensiques", "field": "أسلاك نظامية وعسكرية"},
  {"slug": "cherchall", "ar": "الأكاديمية العسكرية بشرشال", "fr": "EMIA", "field": "أسلاك نظامية وعسكرية"},
  {"slug": "military-media", "ar": "المدرسة العليا العسكرية للإعلام والاتصال", "fr": "سيدي فرج، الجزائر العاصمة", "field": "أسلاك نظامية وعسكرية"},
  {"slug": "commissariat-corps", "ar": "المدرسة العليا لتقنيات المعتمدية", "fr": "البليدة", "field": "أسلاك نظامية وعسكرية"},
  {"slug": "signal-corps", "ar": "المدرسة العليا للإشارة", "fr": "القليعة، تيبازة", "field": "أسلاك نظامية وعسكرية"},
  {"slug": "esdat", "ar": "المدرسة العليا للدفاع الجوي عن الإقليم ESDAT", "fr": "الرغاية", "field": "أسلاك نظامية وعسكرية"},
  {"slug": "ordnance-corps", "ar": "المدرسة العليا للعتاد", "fr": "الحراش، الجزائر العاصمة", "field": "أسلاك نظامية وعسكرية"},
  {"slug": "digital-eng", "ar": "إدارة رقمية وإلكترونية + إنجليزية | DIGITAL ADMINISTRATION & GLOBAL MANAGEMENT", "fr": "", "field": "إعلام آلي ورقمنة"},
  {"slug": "health-info", "ar": "إدارة نظم المعلومات الصحية", "fr": "Health Information Systems Management", "field": "إعلام آلي ورقمنة"},
  {"slug": "digital-prod", "ar": "إنتاج وتصميم رقمي", "fr": "Digital Content Production", "field": "إعلام آلي ورقمنة"},
  {"slug": "informatique", "ar": "الإعلام الآلي - INFORMATIQUE", "fr": "", "field": "إعلام آلي ورقمنة"},
  {"slug": "digital-biz", "ar": "الاتصال الرقمي وإدارة الأعمال", "fr": "Digital Communication & Business Administration", "field": "إعلام آلي ورقمنة"},
  {"slug": "history-data", "ar": "التاريخ والبيانات الضخمة", "fr": "History & Big Data", "field": "إعلام آلي ورقمنة"},
  {"slug": "it-int", "ar": "التشغيل البيني لأنظمة المعلومات", "fr": "Information Systems Interoperability", "field": "إعلام آلي ورقمنة"},
  {"slug": "cinema-media", "ar": "السينما والميديا الرقمية", "fr": "Cinema & Digital Media", "field": "إعلام آلي ورقمنة"},
  {"slug": "enssn", "ar": "المدرسة العليا في علوم النانو و تكنولوجيا النانو - ENSSN", "fr": "", "field": "إعلام آلي ورقمنة"},
  {"slug": "estin", "ar": "المدرسة العليا لعلوم و تكنولوجيات الإعلام الآلي و الرقمنة - ESTIN", "fr": "", "field": "إعلام آلي ورقمنة"},
  {"slug": "enscs", "ar": "المدرسة العليا للأمن السيبيراني - ENSCS", "fr": "", "field": "إعلام آلي ورقمنة"},
  {"slug": "esi-alger", "ar": "المدرسة العليا للإعلام الآلي", "fr": "ESI الجزائر العاصمة", "field": "إعلام آلي ورقمنة"},
  {"slug": "esi-sba", "ar": "المدرسة العليا للإعلام الآلي", "fr": "ESI سيدي بلعباس", "field": "إعلام آلي ورقمنة"},
  {"slug": "ensia", "ar": "المدرسة العليا للذكاء الإصطناعي - ENSIA", "fr": "", "field": "إعلام آلي ورقمنة"},
  {"slug": "esi-kolea", "ar": "المدرسة العليا للضرائب", "fr": "ESI قليعة", "field": "إعلام آلي ورقمنة"},
  {"slug": "ensta", "ar": "المدرسة الوطنية العليا للتكنولوجيات المتقدمة", "fr": "ENSTA (إعلام آلي) درقانة", "field": "إعلام آلي ورقمنة"},
  {"slug": "digital-agro", "ar": "الهندسة الزراعية الرقمية", "fr": "Digital Agronomy", "field": "إعلام آلي ورقمنة"},
  {"slug": "genomic-data", "ar": "علم البيانات الجينية", "fr": "Genomic Data Science", "field": "إعلام آلي ورقمنة"},
  {"slug": "info-auto", "ar": "مزدوج: إعلام آلي + آلية", "fr": "COMPUTER SCIENCE & AUTOMATIC (ROBOTICS)", "field": "إعلام آلي ورقمنة"},
  {"slug": "cs-eco", "ar": "مزدوج: إعلام آلي + علوم اقتصادية | COMPUTER SCIENCE & ECONOMICS (FINTECH)", "fr": "", "field": "إعلام آلي ورقمنة"},
  {"slug": "tech-media", "ar": "مزدوج: إعلام آلي + علوم الإعلام والاتصال | TECH-MEDIA & DIGITAL COMMUNICATIONS", "fr": "", "field": "إعلام آلي ورقمنة"},
  {"slug": "info-gest", "ar": "مزدوج: إعلام آلي + علوم التسيير", "fr": "COMPUTER SCIENCE & MANAGEMENT", "field": "إعلام آلي ورقمنة"},
  {"slug": "droit-info", "ar": "مزدوج: حقوق + إعلام آلي", "fr": "LAW & COMPUTER SCIENCE", "field": "إعلام آلي ورقمنة"},
  {"slug": "3d-design", "ar": "مصمم ثلاثي الأبعاد", "fr": "3D Design & VFX", "field": "إعلام آلي ورقمنة"},
  {"slug": "lang-fin", "ar": "آداب ولغات أجنبية + محاسبة وعلوم مالية", "fr": "LANGUAGES & FINANCIAL ACCOUNTING", "field": "اقتصاد وتسيير"},
  {"slug": "e-commerce", "ar": "إدارة وتسيير العمليات التجارية الإلكترونية (E-Commerce)", "fr": "", "field": "اقتصاد وتسيير"},
  {"slug": "eco-ir", "ar": "إقتصاد + علاقات دولية", "fr": "Double Diplôme", "field": "اقتصاد وتسيير"},
  {"slug": "e-biz", "ar": "الإدارة الإلكترونية للأعمال", "fr": "E-Business / E-Management", "field": "اقتصاد وتسيير"},
  {"slug": "marketing-comm", "ar": "الاتصال التسويقي وإدارة العلاقات مع الزبائن", "fr": "MarCom & CRM", "field": "اقتصاد وتسيير"},
  {"slug": "comm-tourism", "ar": "الاتصال السياحي والترويج للأقاليم", "fr": "Tourism Communication & Territorial Branding", "field": "اقتصاد وتسيير"},
  {"slug": "iedf", "ar": "الاقتصاد الجبائي والجمركي", "fr": "IEDF", "field": "اقتصاد وتسيير"},
  {"slug": "trading", "ar": "التداول والأسواق المالية", "fr": "Trading & Financial Markets", "field": "اقتصاد وتسيير"},
  {"slug": "fintech", "ar": "التفاوض والتكنولوجيا المالية", "fr": "Negotiation & FinTech", "field": "اقتصاد وتسيير"},
  {"slug": "eco", "ar": "العلوم الاقتصادية", "fr": "Sciences Économiques", "field": "اقتصاد وتسيير"},
  {"slug": "segc", "ar": "العلوم الاقتصادية والتسيير والعلوم التجارية (SEGC)", "fr": "", "field": "اقتصاد وتسيير"},
  {"slug": "commerce", "ar": "العلوم التجارية", "fr": "Sciences Commerciales", "field": "اقتصاد وتسيير"},
  {"slug": "esaa", "ar": "المدرسة العليا الجزائرية للأعمال", "fr": "ESAA", "field": "اقتصاد وتسيير"},
  {"slug": "essg", "ar": "المدرسة العليا لعلوم التسيير", "fr": "ESSG عنابة", "field": "اقتصاد وتسيير"},
  {"slug": "ese", "ar": "المدرسة العليا للاقتصاد", "fr": "ESE وهران", "field": "اقتصاد وتسيير"},
  {"slug": "ensc", "ar": "المدرسة العليا للتجارة - ENSC", "fr": "", "field": "اقتصاد وتسيير"},
  {"slug": "esgen", "ar": "المدرسة العليا للتسيير والاقتصاد الرقمي - ESGEN", "fr": "", "field": "اقتصاد وتسيير"},
  {"slug": "ehec", "ar": "المدرسة العليا للدراسات التجارية - EHEC", "fr": "", "field": "اقتصاد وتسيير"},
  {"slug": "enst", "ar": "المدرسة العليا للسياحة", "fr": "ENST الجزائر", "field": "اقتصاد وتسيير"},
  {"slug": "escf", "ar": "المدرسة العليا للمحاسبة والمالية", "fr": "ESCF قسنطينة", "field": "اقتصاد وتسيير"},
  {"slug": "esb", "ar": "المدرسة العليا للمصرفة والبنوك", "fr": "ESB الجزائر", "field": "اقتصاد وتسيير"},
  {"slug": "esm", "ar": "المدرسة العليا للمناجمنت", "fr": "ESM تلمسان", "field": "اقتصاد وتسيير"},
  {"slug": "ensm", "ar": "المدرسة الوطنية العليا للمناجمنت", "fr": "ENSM القليعة", "field": "اقتصاد وتسيير"},
  {"slug": "csr", "ar": "المسؤولية المجتمعية للشركات", "fr": "Corporate Social Responsibility (CSR)", "field": "اقتصاد وتسيير"},
  {"slug": "gtu", "ar": "تسيير التقنيات الحضرية (Gestion des Techniques Urbaines - GTU)", "fr": "", "field": "اقتصاد وتسيير"},
  {"slug": "business-computing", "ar": "حوسبة الأعمال (Business Computing)", "fr": "", "field": "اقتصاد وتسيير"},
  {"slug": "loisir", "ar": "علم الاجتماع", "fr": "السياحة والرفاهية – Sociologie du Loisir", "field": "اقتصاد وتسيير"},
  {"slug": "eco-media", "ar": "علوم اقتصادية + علوم الإعلام والاتصال | ECONOMIC JOURNALISM & MARKETING", "fr": "", "field": "اقتصاد وتسيير"},
  {"slug": "gestion", "ar": "علوم التسيير", "fr": "Sciences de Gestion", "field": "اقتصاد وتسيير"},
  {"slug": "law-fin", "ar": "مزدوج: حقوق + علوم مالية ومحاسبة | LAW & FINANCE", "fr": "", "field": "اقتصاد وتسيير"},
  {"slug": "mgmt-eng", "ar": "مزدوج: علوم التسيير + لغة إنجليزية", "fr": "MANAGEMENT & ENGLISH", "field": "اقتصاد وتسيير"},
  {"slug": "ufc", "ar": "جامعة التكوين المتواصل (UFC)", "fr": "", "field": "تخصّصات أخرى"},
  {"slug": "ens-info-lycee", "ar": "أستاذ التعليم الثانوي في الإعلام الآلي", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-history-lycee", "ar": "أستاذ التعليم الثانوي في التاريخ والجغرافيا", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-sport-lycee", "ar": "أستاذ التعليم الثانوي في التربية البدنية والرياضية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-music-lycee", "ar": "أستاذ التعليم الثانوي في التربية الموسيقية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-art-lycee", "ar": "أستاذ التعليم الثانوي في الرسم / التربية الفنية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-math-lycee", "ar": "أستاذ التعليم الثانوي في الرياضيات", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-islamic-lycee", "ar": "أستاذ التعليم الثانوي في العلوم الإسلامية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-economy-lycee", "ar": "أستاذ التعليم الثانوي في العلوم الاقتصادية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-science-lycee", "ar": "أستاذ التعليم الثانوي في العلوم الطبيعية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-physics-lycee", "ar": "أستاذ التعليم الثانوي في العلوم الفيزيائية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-philosophy-lycee", "ar": "أستاذ التعليم الثانوي في الفلسفة", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-german-lycee", "ar": "أستاذ التعليم الثانوي في اللغة الألمانية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-tamazight-lycee", "ar": "أستاذ التعليم الثانوي في اللغة الأمازيغية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-spanish-lycee", "ar": "أستاذ التعليم الثانوي في اللغة الإسبانية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-english-lycee", "ar": "أستاذ التعليم الثانوي في اللغة الإنجليزية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-italian-lycee", "ar": "أستاذ التعليم الثانوي في اللغة الإيطالية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-french-lycee", "ar": "أستاذ التعليم الثانوي في اللغة الفرنسية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-arabic-lycee", "ar": "أستاذ التعليم الثانوي في اللغة والأدب العربي", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-electrical-lycee", "ar": "أستاذ التعليم الثانوي في الهندسة الكهربائية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-civil-lycee", "ar": "أستاذ التعليم الثانوي في الهندسة المدنية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-mechanics-lycee", "ar": "أستاذ التعليم الثانوي في الهندسة الميكانيكية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-process-eng-lycee", "ar": "أستاذ التعليم الثانوي في هندسة الطرائق", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-info-moyen", "ar": "أستاذ التعليم المتوسط في الإعلام الآلي", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-history-moyen", "ar": "أستاذ التعليم المتوسط في التاريخ والجغرافيا", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-islamic-moyen", "ar": "أستاذ التعليم المتوسط في التربية الإسلامية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-sport-moyen", "ar": "أستاذ التعليم المتوسط في التربية البدنية والرياضية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-music-moyen", "ar": "أستاذ التعليم المتوسط في التربية الموسيقية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-art-moyen", "ar": "أستاذ التعليم المتوسط في الرسم والتربية الفنية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-math-moyen", "ar": "أستاذ التعليم المتوسط في الرياضيات", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-science-moyen", "ar": "أستاذ التعليم المتوسط في العلوم الطبيعية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-physics-moyen", "ar": "أستاذ التعليم المتوسط في العلوم الفيزيائية والتكنولوجيا", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-tamazight-moyen", "ar": "أستاذ التعليم المتوسط في اللغة الأمازيغية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-english-moyen", "ar": "أستاذ التعليم المتوسط في اللغة الإنجليزية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-french-moyen", "ar": "أستاذ التعليم المتوسط في اللغة الفرنسية", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-arabic-moyen", "ar": "أستاذ التعليم المتوسط في اللغة والأدب العربي", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-anglais-primaire", "ar": "المدارس العليا للأساتذة - ENS", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-francais-primaire", "ar": "المدارس العليا للأساتذة - ENS", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-sport-primaire", "ar": "المدارس العليا للأساتذة - ENS", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens-tamazight-primaire", "ar": "المدارس العليا للأساتذة - ENS", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "ens", "ar": "المدارس العليا للأساتذة - ENS", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "esesm", "ar": "المدرسة العليا لأساتذة الصم والبكم - ESESM بني مسوس", "fr": "", "field": "تعليم وتكوين أساتذة"},
  {"slug": "comm-ir", "ar": "إتصال + علاقات دولية", "fr": "Double Diplôme", "field": "حقوق وعلوم سياسية"},
  {"slug": "droit", "ar": "الحقوق", "fr": "Droit", "field": "حقوق وعلوم سياسية"},
  {"slug": "idri", "ar": "الدبلوماسية والعلاقات الدولية", "fr": "IDRI", "field": "حقوق وعلوم سياسية"},
  {"slug": "sciences-po", "ar": "العلوم السياسية", "fr": "Sciences Politiques", "field": "حقوق وعلوم سياسية"},
  {"slug": "penal", "ar": "القانون الجنائي والعلوم الجنائية", "fr": "Droit Pénal", "field": "حقوق وعلوم سياسية"},
  {"slug": "essp", "ar": "المدرسة العليا للعلوم السياسية", "fr": "ESSP", "field": "حقوق وعلوم سياسية"},
  {"slug": "esm-justice", "ar": "المدرسة العليا للقضاء", "fr": "ESM", "field": "حقوق وعلوم سياسية"},
  {"slug": "ena", "ar": "المدرسة الوطنية للإدارة", "fr": "ENA", "field": "حقوق وعلوم سياسية"},
  {"slug": "public-innov", "ar": "دراسات وابتكار عمومي", "fr": "Public Studies & Innovation", "field": "حقوق وعلوم سياسية"},
  {"slug": "criminologie", "ar": "علم الإجرام والسياسة الجنائية", "fr": "Criminologie", "field": "حقوق وعلوم سياسية"},
  {"slug": "media-pol", "ar": "علوم الإعلام والاتصال + علوم سياسية | POLITICAL COMMUNICATION & PUBLIC RELATIONS (PR)", "fr": "", "field": "حقوق وعلوم سياسية"},
  {"slug": "dip-law", "ar": "قانون دبلوماسي + تعاون دولي | DIPLOMATIC LAW & INTERNATIONAL COOPERATION", "fr": "", "field": "حقوق وعلوم سياسية"},
  {"slug": "law-ir", "ar": "قانون عام + علاقات دولية", "fr": "Double Diplôme", "field": "حقوق وعلوم سياسية"},
  {"slug": "scenario", "ar": "كتابة السيناريو", "fr": "Screenwriting / Creative Writing", "field": "حقوق وعلوم سياسية"},
  {"slug": "law-pol", "ar": "مزدوج: حقوق + علوم سياسية", "fr": "LAW & POLITICAL SCIENCE", "field": "حقوق وعلوم سياسية"},
  {"slug": "eng-pol", "ar": "مزدوج: لغة إنجليزية + علوم سياسية | ENGLISH & POLITICAL SCIENCE (GLOBAL DIPLOMACY)", "fr": "", "field": "حقوق وعلوم سياسية"},
  {"slug": "dent-hyg", "ar": "أخصائي في صحة ونظافة الأسنان", "fr": "Dental Hygienist", "field": "صحّة وطبّ"},
  {"slug": "anesthesie-reanimation", "ar": "التخدير والإنعاش", "fr": "Anesthésie-Réanimation", "field": "صحّة وطبّ"},
  {"slug": "med-info", "ar": "التخصص المزدوج: طب + إعلام آلي", "fr": "Double Cursus Médecine + Informatique", "field": "صحّة وطبّ"},
  {"slug": "med-ai", "ar": "الذكاء الاصطناعي الطبي", "fr": "Medical AI", "field": "صحّة وطبّ"},
  {"slug": "math-app", "ar": "الرياضيات التطبيقية (Mathématiques Appliquées)", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "paramedical", "ar": "الشبه طبي - PARAMEDICAL", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "health-soc", "ar": "الصحة والحماية الاجتماعية", "fr": "Santé et Protection Sociale", "field": "صحّة وطبّ"},
  {"slug": "pharmacie", "ar": "الصيدلة - PHARMACIE", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "pharmacie-industrielle", "ar": "الصيدلة الصناعية", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "medcine", "ar": "الطب - MEDCINE", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "vetrinaire", "ar": "الطب البيطري - vetrinaire", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "prec-med", "ar": "الطب الدقيق", "fr": "Precision Medicine", "field": "صحّة وطبّ"},
  {"slug": "pharma-prep", "ar": "المحضرون في الصيدلة للصحة العمومية", "fr": "Préparateurs en Pharmacie", "field": "صحّة وطبّ"},
  {"slug": "public-health-hygiene", "ar": "المختصون في حفظ الصحة للصحة العمومية | Hygiène et Santé Publique", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "ensb", "ar": "المدرسة العليا للبيوتكنولوجيا  - ENSB", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "enste", "ar": "المدرسة العليا للعلوم التطبيقية", "fr": "ESSA", "field": "صحّة وطبّ"},
  {"slug": "essa", "ar": "المدرسة العليا للعلوم التطبيقية", "fr": "ESSA", "field": "صحّة وطبّ"},
  {"slug": "enmas", "ar": "المدرسة العليا للمناجمنت وإدارة الصحة", "fr": "ENMAS", "field": "صحّة وطبّ"},
  {"slug": "enssea", "ar": "المدرسة الوطنية العليا للإحصاء والاقتصاد التطبيقي - ENSSEA", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "assistant-social", "ar": "المساعدون الاجتماعيون للصحة العمومية | Assistants Sociaux", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "adjoint-medical", "ar": "المساعدون الطبيون للصحة العمومية | Adjoints Médicaux", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "med-informatics", "ar": "المعلوماتية الطبية", "fr": "Medical Informatics", "field": "صحّة وطبّ"},
  {"slug": "biomedical", "ar": "الهندسة البيوطبية - Génie Biomédical", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "radio", "ar": "بتخصص مشغل أجهزة التصوير الطبي للصحة العمومية | Technicien en imagerie médicale", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "optique", "ar": "بصريات وميكانيك الدقة - Optique & Mécanique de précision", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "mi-social", "ar": "رياضيات وإعلام آلي مطبقة في العلوم الإنسانية والاجتماعية (MI)", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "mi-seg", "ar": "رياضيات وإعلام آلي مطبقة في العلوم الاقتصادية والتسيير (MI-SEG)", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "medcine-dentaire", "ar": "طب الأسنان - MEDCINE DENTAIRE", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "addict", "ar": "علم الإدمان", "fr": "Addictology", "field": "صحّة وطبّ"},
  {"slug": "med-gen", "ar": "علم الوراثة الطبية", "fr": "Medical Genetics", "field": "صحّة وطبّ"},
  {"slug": "sage-femme", "ar": "قابلة الصحة العمومية", "fr": "Sage-Femme", "field": "صحّة وطبّ"},
  {"slug": "labo", "ar": "مخبري للصحة العمومية | Laborantin de santé publique", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "dieteticien", "ar": "مختص في التغذية للصحة العمومية", "fr": "Diététicien", "field": "صحّة وطبّ"},
  {"slug": "kine", "ar": "مختص في العلاج الطبيعي و الفيزيائي | La kinésithérapie", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "esp", "ar": "مداوٍ بالعمل للصحة العمومية | Ergothérapie", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "dental-prosthetist", "ar": "مرمم الأسنان للصحة العمومية", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "med-bio", "ar": "مزدوج طب + بيولوجيا", "fr": "Médecine + Biologie", "field": "صحّة وطبّ"},
  {"slug": "med-eco", "ar": "مزدوج: الطب + اقتصاد الصحة", "fr": "MÉDECINE & ÉCONOMIE DE LA SANTÉ", "field": "صحّة وطبّ"},
  {"slug": "med-psy", "ar": "مزدوج: الطب + علم النفس العيادي", "fr": "MÉDECINE & PSYCHOLOGIE CLINIQUE", "field": "صحّة وطبّ"},
  {"slug": "math-eco", "ar": "مزدوج: رياضيات تطبيقية + علوم اقتصادية", "fr": "APPLIED MATHEMATICS & ECONOMICS", "field": "صحّة وطبّ"},
  {"slug": "gen-couns", "ar": "مستشار في علم الوراثة", "fr": "Genetic Counselor", "field": "صحّة وطبّ"},
  {"slug": "pedicure-podologue", "ar": "مطبب الأرجل للصحة العمومية | Pédicure Podologue de Santé Publique", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "appareilleur-orthopediste", "ar": "مقوم الأعضاء الاصطناعية للصحة العمومية | Appareilleur Orthopédiste", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "psychomotricien", "ar": "مقومو الحركة النفسية للصحة العمومية | Psychomotricien de la santé publique", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "isp", "ar": "ممرض الصحة العمومية (ISP)", "fr": "", "field": "صحّة وطبّ"},
  {"slug": "health-comm", "ar": "الإعلام والاتصال الصحي", "fr": "Health Communication", "field": "علوم إنسانية واجتماعية"},
  {"slug": "childhood", "ar": "التربية والنفس حركية لمرحلة الطفولة", "fr": "Psychomotor Education & Early Childhood", "field": "علوم إنسانية واجتماعية"},
  {"slug": "geographie", "ar": "الجغرافيا", "fr": "Géographie", "field": "علوم إنسانية واجتماعية"},
  {"slug": "charia", "ar": "العلوم الإسلامية", "fr": "Sciences Islamiques", "field": "علوم إنسانية واجتماعية"},
  {"slug": "sciences-hum", "ar": "العلوم الإنسانية", "fr": "Sciences Humaines", "field": "علوم إنسانية واجتماعية"},
  {"slug": "ss", "ar": "العلوم الاجتماعية", "fr": "Sciences Sociales", "field": "علوم إنسانية واجتماعية"},
  {"slug": "sociales", "ar": "العلوم الاجتماعية", "fr": "Sciences Sociales", "field": "علوم إنسانية واجتماعية"},
  {"slug": "philo", "ar": "الفلسفة", "fr": "Philosophie", "field": "علوم إنسانية واجتماعية"},
  {"slug": "esss", "ar": "المدرسة العليا للضمان الاجتماعي", "fr": "ESSS", "field": "علوم إنسانية واجتماعية"},
  {"slug": "ensjsi", "ar": "المدرسة الوطنية العليا للصحافة وعلوم الإعلام", "fr": "ENSJSI", "field": "علوم إنسانية واجتماعية"},
  {"slug": "soc-leisure", "ar": "علم الاجتماع الترفيه والأسفار", "fr": "Sociology of Leisure & Travel", "field": "علوم إنسانية واجتماعية"},
  {"slug": "commu", "ar": "علوم الإعلام والاتصال", "fr": "Sciences de l'Information et de la Communication", "field": "علوم إنسانية واجتماعية"},
  {"slug": "staps", "ar": "STAPS", "fr": "علوم وتقنيات الأنشطة البدنية والرياضية", "field": "علوم الرياضة"},
  {"slug": "sports-psych", "ar": "تدريب رياضي + علم النفس العيادي | SPORTS PSYCHOLOGY & HIGH PERFORMANCE", "fr": "", "field": "علوم الرياضة"},
  {"slug": "sports-media", "ar": "علوم الإعلام والاتصال + تدريب رياضي | SPORTS JOURNALISM & PERFORMANCE ANALYTICS", "fr": "", "field": "علوم الرياضة"},
  {"slug": "biologie", "ar": "البيولوجيا - BIOLOGIE", "fr": "", "field": "علوم دقيقة"},
  {"slug": "geologie", "ar": "الجيولوجيا", "fr": "Géologie", "field": "علوم دقيقة"},
  {"slug": "essbo", "ar": "المدرسة العليا للعلوم البيولوجية", "fr": "ESSBO وهران", "field": "علوم دقيقة"},
  {"slug": "nhsm", "ar": "المدرسة الوطنية العليا للرياضيات - NHSM", "fr": "", "field": "علوم دقيقة"},
  {"slug": "math", "ar": "رياضيات - MATH", "fr": "", "field": "علوم دقيقة"},
  {"slug": "sm", "ar": "علوم المادة - SM", "fr": "", "field": "علوم دقيقة"},
  {"slug": "circular-economy", "ar": "الاقتصاد الدائري وإعادة التدوير", "fr": "Circular Economy & Recycling", "field": "فلاحة وبيئة"},
  {"slug": "proteins-seeds", "ar": "البروتينات والبذور", "fr": "Proteins & Seeds", "field": "فلاحة وبيئة"},
  {"slug": "inataa", "ar": "التغذية و الصناعات الفلاحية الغذائية", "fr": "INATAA قسنطينة", "field": "فلاحة وبيئة"},
  {"slug": "agronomie", "ar": "العلوم الزراعية", "fr": "Sciences Agronomiques", "field": "فلاحة وبيئة"},
  {"slug": "agro", "ar": "العلوم الفلاحية", "fr": "Sciences Agronomiques", "field": "فلاحة وبيئة"},
  {"slug": "essaia", "ar": "المدرسة العليا لعلوم التغذية والصناعات الغذائية - ESSAIA", "fr": "", "field": "فلاحة وبيئة"},
  {"slug": "ensa", "ar": "المدرسة العليا للفلاحة - ENSA", "fr": "", "field": "فلاحة وبيئة"},
  {"slug": "enssmal", "ar": "المدرسة الوطنية العليا لعلوم البحر وتهيئة الساحل - ENSSMAL", "fr": "", "field": "فلاحة وبيئة"},
  {"slug": "ensh", "ar": "المدرسة الوطنية العليا للري", "fr": "ENSH البليدة", "field": "فلاحة وبيئة"},
  {"slug": "ensf", "ar": "المدرسة الوطنية العليا للغابات", "fr": "ENSF خنشلة", "field": "فلاحة وبيئة"},
  {"slug": "env-sci", "ar": "علوم البيئة والمحيط", "fr": "Environmental Sciences", "field": "فلاحة وبيئة"},
  {"slug": "agroalimentaire", "ar": "علوم الغذاء والتغذية", "fr": "Sciences Alimentaires (LMD)", "field": "فلاحة وبيئة"},
  {"slug": "ind-entr", "ar": "السينما والمقاولاتية", "fr": "CINÉMA & ENTREPRENEURIAT", "field": "فنون وتصميم"},
  {"slug": "cinema", "ar": "السينما وفنون العرض", "fr": "Cinéma", "field": "فنون وتصميم"},
  {"slug": "arts", "ar": "الفنون التشكيلية", "fr": "Arts Plastiques", "field": "فنون وتصميم"},
  {"slug": "ensrpc", "ar": "المدرسة الوطنية العليا لحفظ الممتلكات الثقافية وترميمها", "fr": "ENSRPC", "field": "فنون وتصميم"},
  {"slug": "enscrbc", "ar": "المدرسة الوطنية العليا لحفظ الممتلكات الثقافية وترميمها", "fr": "ENSCRBC", "field": "فنون وتصميم"},
  {"slug": "archeologie", "ar": "علم الآثار", "fr": "Archéologie", "field": "فنون وتصميم"},
  {"slug": "music-perf", "ar": "متحكم في الأداء الموسيقي والإبداع الفني", "fr": "Musical Performance & Artistic Direction", "field": "فنون وتصميم"},
  {"slug": "theater", "ar": "ممثل محترف وكاتب مسرحي", "fr": "Acting & Playwriting", "field": "فنون وتصميم"},
  {"slug": "traduction", "ar": "الترجمة", "fr": "Traduction", "field": "لغات وآداب"},
  {"slug": "langues", "ar": "اللغات الأجنبية", "fr": "Langues Étrangères", "field": "لغات وآداب"},
  {"slug": "arabe", "ar": "اللغة والأدب العربي", "fr": "Langue et Littérature Arabes", "field": "لغات وآداب"},
  {"slug": "tamazight", "ar": "اللغة والثقافة الأمازيغية", "fr": "Langue et Culture Tamazightes", "field": "لغات وآداب"},
  {"slug": "allemand", "ar": "ليسانس اللغة الألمانية", "fr": "Allemand", "field": "لغات وآداب"},
  {"slug": "espagnol", "ar": "ليسانس اللغة الإسبانية", "fr": "Espagnol", "field": "لغات وآداب"},
  {"slug": "anglais", "ar": "ليسانس اللغة الإنجليزية", "fr": "Anglais", "field": "لغات وآداب"},
  {"slug": "italien", "ar": "ليسانس اللغة الإيطالية", "fr": "Italien", "field": "لغات وآداب"},
  {"slug": "turc", "ar": "ليسانس اللغة التركية", "fr": "Turc", "field": "لغات وآداب"},
  {"slug": "russe", "ar": "ليسانس اللغة الروسية", "fr": "Russe", "field": "لغات وآداب"},
  {"slug": "chinois", "ar": "ليسانس اللغة الصينية", "fr": "Chinois", "field": "لغات وآداب"},
  {"slug": "francais", "ar": "ليسانس اللغة الفرنسية", "fr": "Français", "field": "لغات وآداب"},
  {"slug": "aeroport", "ar": "إدارة المطارات والعبور", "fr": "Management Aéroportuaire & Transit", "field": "هندسة وتكنولوجيا"},
  {"slug": "auto", "ar": "الآلية والتحكم الآلي", "fr": "Automatique", "field": "هندسة وتكنولوجيا"},
  {"slug": "igee", "ar": "الإلكترونيك بومرداس - IGEE", "fr": "", "field": "هندسة وتكنولوجيا"},
  {"slug": "telecom", "ar": "الاتصالات السلكية واللاسلكية", "fr": "Télécommunications", "field": "هندسة وتكنولوجيا"},
  {"slug": "renouvelables", "ar": "الطاقات المتجددة (Énergies Renouvelables)", "fr": "", "field": "هندسة وتكنولوجيا"},
  {"slug": "urbanisme", "ar": "العمران (Urbanisme) - N04LAL01", "fr": "", "field": "هندسة وتكنولوجيا"},
  {"slug": "quantum", "ar": "الفيزياء الكمومية وميكانيك الكم", "fr": "Quantum Physics", "field": "هندسة وتكنولوجيا"},
  {"slug": "electro", "ar": "الكهروتقني", "fr": "Électrotechnique", "field": "هندسة وتكنولوجيا"},
  {"slug": "hydrocarbures", "ar": "المحروقات - HYDROCARBURES", "fr": "", "field": "هندسة وتكنولوجيا"},
  {"slug": "enstp", "ar": "المدرسة العليا للأشغال العمومية - ENSTP", "fr": "", "field": "هندسة وتكنولوجيا"},
  {"slug": "ensas", "ar": "المدرسة العليا للأنظمة المستقلة", "fr": "NHSAST", "field": "هندسة وتكنولوجيا"},
  {"slug": "ensmar", "ar": "المدرسة العليا للبحرية ENSM", "fr": "برج البحري", "field": "هندسة وتكنولوجيا"},
  {"slug": "esa", "ar": "المدرسة العليا للطيران ESA", "fr": "وهران", "field": "هندسة وتكنولوجيا"},
  {"slug": "esgee", "ar": "المدرسة العليا للهندسة الكهربائية والطاقوية", "fr": "ESGEE وهران", "field": "هندسة وتكنولوجيا"},
  {"slug": "enpei", "ar": "المدرسة الوطنية التحضيرية لدراسات مهندس", "fr": "ENPEI رويبة", "field": "هندسة وتكنولوجيا"},
  {"slug": "ensttic", "ar": "المدرسة الوطنية العليا للاتصالات وتكنولوجيا الإعلام والاتصال - ENSTTIC", "fr": "", "field": "هندسة وتكنولوجيا"},
  {"slug": "ensta-st", "ar": "المدرسة الوطنية العليا للتكنولوجيا المتقدمة - ENSTA الجزائر (علوم وتكنولوجيا)", "fr": "", "field": "هندسة وتكنولوجيا"},
  {"slug": "hnsre", "ar": "المدرسة الوطنية العليا للطاقات المتجددة والبيئة والتنمية المستدامة", "fr": "HNSRE باتنة", "field": "هندسة وتكنولوجيا"},
  {"slug": "polytech", "ar": "المدرسة الوطنية متعددة التقنيات - POLYTECH", "fr": "", "field": "هندسة وتكنولوجيا"},
  {"slug": "epau", "ar": "المدرسة متعددة التقنيات  للهندسة المعمارية والعمران", "fr": "EPAU", "field": "هندسة وتكنولوجيا"},
  {"slug": "smart-cities", "ar": "المدن الذكية", "fr": "Smart Cities", "field": "هندسة وتكنولوجيا"},
  {"slug": "petrochimie", "ar": "الهندسة البتروكيميائية", "fr": "Génie Pétrochimique", "field": "هندسة وتكنولوجيا"},
  {"slug": "marine", "ar": "الهندسة البحرية", "fr": "Marine Engineering", "field": "هندسة وتكنولوجيا"},
  {"slug": "gi", "ar": "الهندسة الصناعية", "fr": "Génie Industriel", "field": "هندسة وتكنولوجيا"},
  {"slug": "gc", "ar": "الهندسة المدنية", "fr": "Génie Civil", "field": "هندسة وتكنولوجيا"},
  {"slug": "architecture-uni", "ar": "الهندسة المعمارية", "fr": "", "field": "هندسة وتكنولوجيا"},
  {"slug": "gmec", "ar": "الهندسة الميكانيكية", "fr": "Génie Mécanique", "field": "هندسة وتكنولوجيا"},
  {"slug": "hydro", "ar": "الهندسة الهيدروليكية والري", "fr": "Hydraulique", "field": "هندسة وتكنولوجيا"},
  {"slug": "hse", "ar": "الوقاية والأمن الصناعي", "fr": "HSE", "field": "هندسة وتكنولوجيا"},
  {"slug": "space-tech", "ar": "تكنولوجيا الفضاء", "fr": "Space Technology", "field": "هندسة وتكنولوجيا"},
  {"slug": "st", "ar": "علوم و تكنولوجيا - ST", "fr": "", "field": "هندسة وتكنولوجيا"},
  {"slug": "arch-soc", "ar": "مزدوج: هندسة معمارية + علم الاجتماع | ARCHITECTURE & URBAN SOCIOLOGY", "fr": "", "field": "هندسة وتكنولوجيا"},
  {"slug": "city-jobs", "ar": "مهن المدينة", "fr": "Métiers de la Ville", "field": "هندسة وتكنولوجيا"},
  {"slug": "gm", "ar": "هندسة التعدين", "fr": "Génie Minier", "field": "هندسة وتكنولوجيا"},
  {"slug": "molecular-engineering", "ar": "هندسة الجزيئات الذكية", "fr": "Smart Molecular Engineering", "field": "هندسة وتكنولوجيا"},
  {"slug": "gp", "ar": "هندسة الطرائق", "fr": "Génie des Procédés", "field": "هندسة وتكنولوجيا"},
  {"slug": "aeronautique", "ar": "هندسة الطيران", "fr": "Aéronautique", "field": "هندسة وتكنولوجيا"},
  {"slug": "gt", "ar": "هندسة النقل", "fr": "Génie du Transport", "field": "هندسة وتكنولوجيا"},
  {"slug": "archi-civil", "ar": "هندسة معمارية + هندسة مدنية | ARCHITECTURAL ENGINEERING (ARCHI-CIVIL)", "fr": "", "field": "هندسة وتكنولوجيا"},
  {"slug": "gendarmerie", "ar": "المدرسة العليا للدرك الوطني — زرالدة", "fr": "École Supérieure de la Gendarmerie Nationale", "field": "أسلاك نظامية وعسكرية"},
  {"slug": "military-health", "ar": "المدرسة الوطنية للصحة العسكرية — عين النعجة", "fr": "École Nationale de Santé Militaire", "field": "أسلاك نظامية وعسكرية"},
  {"slug": "republican-guard", "ar": "المدرسة العليا للحرس الجمهوري — برج الكيفان", "fr": "École Supérieure de la Garde Républicaine", "field": "أسلاك نظامية وعسكرية"},
  {"slug": "biomedical-eng", "ar": "الهندسة البيوطبية", "fr": "Biomedical Engineering", "field": "صحّة وطبّ"},
  {"slug": "marine-eng", "ar": "الهندسة البحرية", "fr": "Marine Engineering", "field": "هندسة وتكنولوجيا"},
  {"slug": "renewable-energy", "ar": "الطاقات المتجددة وتخزين الطاقة", "fr": "Renewable Energy and Energy Storage", "field": "هندسة وتكنولوجيا"},
  {"slug": "industrial-engineering", "ar": "الهندسة الصناعية", "fr": "Industrial Engineering", "field": "هندسة وتكنولوجيا"},
  {"slug": "logistics-engineering", "ar": "هندسة السلسلة اللوجستيكية", "fr": "Logistics Chain Engineering", "field": "اقتصاد وتسيير"},
  {"slug": "food-science", "ar": "علوم الغذاء", "fr": "Food Science", "field": "فلاحة وبيئة"},
  {"slug": "architecture", "ar": "الهندسة المعمارية", "fr": "Architecture", "field": "هندسة وتكنولوجيا"},
  {"slug": "political-science", "ar": "العلوم السياسية", "fr": "Political Science", "field": "حقوق وعلوم سياسية"},
  {"slug": "autonomous-systems", "ar": "تكنولوجيا الأنظمة المستقلة", "fr": "Autonomous Systems Technology", "field": "إعلام آلي ورقمنة"},
  {"slug": "data-science", "ar": "علوم البيانات والذكاء الاصطناعي", "fr": "Data Science and Artificial Intelligence", "field": "إعلام آلي ورقمنة"}
];

export const SPEC_FIELDS: string[] = [...new Set(SPEC_INDEX.map((s) => s.field))].sort(
  (a, b) => a.localeCompare(b, "ar"),
);
